trunk/src/DogsClub.WebUI/Models/Payment.cs
using AutoMapper;
using DogsClub.WebUI.Infrastracture;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using models = DogsClub.WebUI.Models;
namespace DogsClub.WebUI.Models
{
    public class Payment
    {
            public int Id { get; set; }
            //   [Required(ErrorMessage="Пустое значение!")]
            public decimal PaySize { get; set; }
        [Required(ErrorMessage = "Пустое значение!")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
            public System.DateTime PayDate { get; set; }
            public string Description { get; set; }
            public int UserId { get; set; }
            public int IdType { get; set; }

            public DomainModel.Payment ToDomainModel()
            {
                return Mapper.Map<DomainModel.Payment>(this);
            }

            public models.PaymentType GetType 
            {
                get 
                {
                   List<models.PaymentType> item = Mapper.Map<List<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
                   return item.FirstOrDefault(t => t.Id == this.IdType);
                }           
            }
            public models.User GetUser
            {
                get
                {
                    List<models.User> item = Mapper.Map<List<models.User>>(ServiceFactory.Instance.UserService.GetAll());
                    return item.FirstOrDefault(t => t.Id == this.UserId);
                }
            }



    }
}

trunk/src/DogsClub.WebUI/Models/PaymentType.cs
using AutoMapper;
using DogsClub.WebUI.Infrastracture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using models = DogsClub.WebUI.Models;
namespace DogsClub.WebUI.Models
{
    public class PaymentType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdPeriod { get; set; }

        public DomainModel.PaymentType ToDomainModel()
        {
            return Mapper.Map<DomainModel.PaymentType>(this);
        }

        public models.PaymentsPeriodType GetPeriod
        {
            get
            {
                var rew = ServiceFactory.Instance.PaymentTypesService.GetAllPaymentPeriods().FirstOrDefault(item => item.Id == this.IdPeriod);
                return new PaymentsPeriodType() { Id = rew.Id, Name = rew.Name};
            }
        }
    }
}

trunk/src/DogsClub.WebUI/Controllers/PaymentController.cs
using AutoMapper;
using DogsClub.WebUI.Infrastracture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using models = DogsClub.WebUI.Models;

namespace DogsClub.WebUI.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Add()
        {
            List<models.PaymentType> allPaymentType = Mapper.Map<List<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
            List<models.User> allUser = Mapper.Map<List<models.User>>(ServiceFactory.Instance.UserService.GetAll());
            ViewData["allPaymentType"] = allPaymentType;
            ViewData["allUser"] = allUser;
            return PartialView();
        }

        [HttpPost]
        public ActionResult Add(models.Payment payment)
        {
            List<models.PaymentType> allPaymentType = Mapper.Map<List<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
            List<models.User> allUser = Mapper.Map<List<models.User>>(ServiceFactory.Instance.UserService.GetAll());
            ViewData["allPaymentType"] = allPaymentType;
            ViewData["allUser"] = allUser;
            if (ModelState.IsValid)
            {
                List<models.Payment> allPayment = Mapper.Map<List<models.Payment>>(ServiceFactory.Instance.PaymentsService.GetAll());
                ServiceFactory.Instance.PaymentsService.Add(payment.ToDomainModel());
            }
            return PartialView(payment);
        }

        public ActionResult GetAll()
        {
            IEnumerable<models.Payment> allMed = Mapper.Map<IEnumerable<models.Payment>>(ServiceFactory.Instance.PaymentsService.GetAll());
            return PartialView(allMed);
        }

        public ActionResult Edit(int id)
        {
            if (id != 0)
            {
                List<models.PaymentType> allPaymentType = Mapper.Map<List<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
                List<models.User> allUser = Mapper.Map<List<models.User>>(ServiceFactory.Instance.UserService.GetAll());
                ViewData["allPaymentType"] = allPaymentType;
                ViewData["allUser"] = allUser;

                models.Payment payment = Mapper.Map<models.Payment>(ServiceFactory.Instance.PaymentsService.GetById(id));
                return View(payment);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Edit(models.Payment payment)
        {
            List<models.PaymentType> allPaymentType = Mapper.Map<List<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
            List<models.User> allUser = Mapper.Map<List<models.User>>(ServiceFactory.Instance.UserService.GetAll());
            ViewData["allPaymentType"] = allPaymentType;
            ViewData["allUser"] = allUser;
            if (ModelState.IsValid)
            {
                ServiceFactory.Instance.PaymentsService.Edit(payment.ToDomainModel());
                return RedirectToAction("Index");
            }
            return View(payment);
        }

        public ActionResult Delete(int id)
        {
            if (id == 0)
                throw new ArgumentNullException();

            models.Payment payment = Mapper.Map<models.Payment>(ServiceFactory.Instance.PaymentsService.GetById(id));

            if (payment != null)
            {
                ServiceFactory.Instance.MedicalCaresService.Remove(payment.Id);
            }

            return RedirectToAction("Index");
        }
    }
}

trunk/src/DogsClub.WebUI/Views/Payment/Add.cshtml
@model  DogsClub.WebUI.Models.Payment
@{
    List<SelectListItem> IdType = new List<SelectListItem>();
    if (ViewData["allPaymentType"] != null)
    {
        var a = ViewData["allPaymentType"] as IEnumerable<DogsClub.WebUI.Models.PaymentType>;
        if (a != null)
        {

            IdType.AddRange(a.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString() }));
        }
    }

    List<SelectListItem> UserId = new List<SelectListItem>();
    if (ViewData["allUser"] != null)
    {
        var a = ViewData["allUser"] as IEnumerable<DogsClub.WebUI.Models.User>;
        if (a != null)
        {
            UserId.AddRange(a.Select(t => new SelectListItem() { Text = t.Email, Value = t.Id.ToString() }));
        }
    }
    
}
<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
@using (@Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="ConteinerChengeUser">
        @Html.AntiForgeryToken()

        <div class="NameAdd">Пользователь</div>
        @Html.DropDownList("UserId", UserId, new { @class = "EditText2" })

        <div class="NameAdd">Тип платежа</div>
        @Html.DropDownList("IdType", IdType, new { @class = "EditText2" })

        <div class="NameAdd">Сумма</div>
        @Html.ValidationMessageFor(model => model.PaySize, "", new { @class = "validationMessage" })
        @Html.EditorFor(model => model.PaySize, new { htmlAttributes = new { @class = "EditText2" } })

        <div class="NameAdd">Дата</div>
        @Html.ValidationMessageFor(model => model.PayDate, "", new { @class = "validationMessage" })
        @Html.EditorFor(model => model.PayDate, new { htmlAttributes = new { @class = "EditText2" } })

        <div class="NameAdd">Описание</div>
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "validationMessage" })
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "EditText2" } })

        <input type="submit" value="Добавить" class="btn btn-info" id="AddButton" />
    </div>
}

@section script{
    <script src="~/DatePicker/DataPicker(1-10).js"></script>
    <script src="~/DatePicker/DataPicker(1-11).js"></script>
    <script src="~/DatePicker/MyScriptDatePicker.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $('#PayDate').datepicker({
            dateFormat: 'dd.mm.yy'
        });
        $(function () {
            $("#PayDate").datepicker();
        });
        $('#PayDate').datepicker('option', $.datepicker.regional["ru"]);

        jQuery(function ($) {
            $.datepicker.regional['ru'] = {
                monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                'Октябрь', 'Ноябрь', 'Декабрь'],
                dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                firstDay: 1,
            };
            $.datepicker.setDefaults($.datepicker.regional['ru']);
        });
        $.datepicker.setDefaults($.extend(
          $.datepicker.regional["ru"])
        );
    </script>
}

trunk/src/DogsClub.WebUI/Views/Payment/Edit.cshtml
@model  DogsClub.WebUI.Models.Payment
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";

    List<SelectListItem> IdType = new List<SelectListItem>();
    if (ViewData["allPaymentType"] != null)
    {
        var a = ViewData["allPaymentType"] as IEnumerable<DogsClub.WebUI.Models.PaymentType>;
        if (a != null)
        {

            IdType.AddRange(a.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString(), Selected = t.Id != Model.IdType ? false : true }));
        }
    }

    List<SelectListItem> UserId = new List<SelectListItem>();
    if (ViewData["allUser"] != null)
    {
        var a = ViewData["allUser"] as IEnumerable<DogsClub.WebUI.Models.User>;
        if (a != null)
        {

            UserId.AddRange(a.Select(t => new SelectListItem() { Text = t.LastName + "  " + t.FirstName + "  " + t.MiddleName, Value = t.Id.ToString(), Selected = t.Id != Model.UserId ? false : true }));
        }
    }

}
<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
<div>
    <div class="ConteinerAddExposition">
        @using (@Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="ConteinerChengeUser">
                @Html.AntiForgeryToken()

                <div class="NameAdd">Пользователь</div>
                @Html.DropDownList("UserId", UserId, new { @class = "EditText2" })

                <div class="NameAdd">Тип платежа</div>
                @Html.DropDownList("IdType", IdType, new { @class = "EditText2" })

                <div class="NameAdd">Сумма</div>
                @Html.ValidationMessageFor(model => model.PaySize, "", new { @class = "validationMessage" })
                @Html.EditorFor(model => model.PaySize, new { htmlAttributes = new { @class = "EditText2" } })

                <div class="NameAdd">Дата</div>
                @Html.ValidationMessageFor(model => model.PayDate, "", new { @class = "validationMessage" })
                @Html.EditorFor(model => model.PayDate, new { htmlAttributes = new { @class = "EditText2" } })

                <div class="NameAdd">Описание</div>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "validationMessage" })
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "EditText2" } })

                <input type="submit" value="Добавить" class="btn btn-info" id="AddButton" />
            </div>
        }
        </div>
    </div>

        @section script{
            <script src="~/DatePicker/DataPicker(1-10).js"></script>
            <script src="~/DatePicker/DataPicker(1-11).js"></script>
            <script src="~/DatePicker/MyScriptDatePicker.js"></script>

            <script src="~/Scripts/jquery.validate.min.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
            <script>
                $('#PayDate').datepicker({
                    dateFormat: 'dd.mm.yy'
                });
                $(function () {
                    $("#PayDate").datepicker();
                });
                $('#PayDate').datepicker('option', $.datepicker.regional["ru"]);

                jQuery(function ($) {
                    $.datepicker.regional['ru'] = {
                        monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                        'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                        'Октябрь', 'Ноябрь', 'Декабрь'],
                        dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                        firstDay: 1,
                    };
                    $.datepicker.setDefaults($.datepicker.regional['ru']);
                });
                $.datepicker.setDefaults($.extend(
                  $.datepicker.regional["ru"])
                );
            </script>
        }

trunk/src/DogsClub.WebUI/Views/Payment/GetAll.cshtml
@model IEnumerable<DogsClub.WebUI.Models.Payment>
<link href="~/Content/DataTables-1.10.4/css/jquery.dataTables.css" rel="stylesheet" />
<table class="table table-hover">

    @foreach (var item in Model)
    {
        <tr>
            <td class="ZagValue2">
                @item.GetUser.LastName  @item.GetUser.FirstName  @item.GetUser.MiddleName
            </td>
            <td class="ZagValue2">
                @Html.DisplayFor(modelItem => item.GetType.Name)
            </td>
            <td class="ZagValue2">
                @Html.DisplayFor(modelItem => item.PayDate)
            </td>
            <td class="ZagValue2">
                @Html.DisplayFor(modelItem => item.PaySize)
            </td>
            <td class="ZagValue2">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="ZagValue2">
                @Html.ActionLink("Редактировать", "Edit", "Payment", new { id = item.Id }, false) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

trunk/src/DogsClub.WebUI/Views/Payment/Index.cshtml
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";
}

<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
<div>
    <div class="ConteinerAddExposition">
        @Html.Action("Add", "Payment")
    </div>
    <div class="ConteinerGetAllExposition">
        @Html.Action("GetAll", "Payment")
    </div>
</div>
@section script{
    <script src="~/DatePicker/DataPicker(1-10).js"></script>
    <script src="~/DatePicker/DataPicker(1-11).js"></script>
    <script src="~/DatePicker/MyScriptDatePicker.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $('#PayDate').datepicker({
            dateFormat: 'dd.mm.yy'
        });
        $(function () {
            $("#PayDate").datepicker();
        });
        $('#PayDate').datepicker('option', $.datepicker.regional["ru"]);

        jQuery(function ($) {
            $.datepicker.regional['ru'] = {
                monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                'Октябрь', 'Ноябрь', 'Декабрь'],
                dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                firstDay: 1,
            };
            $.datepicker.setDefaults($.datepicker.regional['ru']);
        });
        $.datepicker.setDefaults($.extend(
          $.datepicker.regional["ru"])
        );
    </script>
}

