trunk/src/DogsClub.WebUI/Models/ExpositionWinner.cs
using AutoMapper;
using DogsClub.WebUI.Infrastracture;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using models = DogsClub.WebUI.Models;
namespace DogsClub.WebUI.Models
{
    public class ExpositionWinner
    {
        public int Id { get; set; }
        [Required(ErrorMessage="Поле не может быть пустым")]
        public int IdExpositionMember { get; set; }
        [Required(ErrorMessage = "Поле не может быть пустым")]
        public int IdAvard { get; set; }
        [Required(ErrorMessage = "Поле не может быть пустым")]
        public int WinnerPlace { get; set; }
        public DomainModel.ExpositionWinner ToDomainModel()
        {
            return Mapper.Map<DomainModel.ExpositionWinner>(this);
        }
        public models.Avard GetAvard
          {
              get
              {
                  List<models.Avard> AllRequest = Mapper.Map<List<models.Avard>>(ServiceFactory.Instance.AvardsService.GetAll().ToList());
                  models.Avard getAvard = AllRequest.FirstOrDefault(t => t.Id == this.IdAvard);
                  return getAvard;
            }
        }

        public models.Dog GetDog
        {
            get
            {
                var member = ServiceFactory.Instance.ExpositionMembersService.GetById(this.IdExpositionMember);
                return Mapper.Map<models.Dog>(ServiceFactory.Instance.DogsService.GetById(member.IdDog));
            }
        }

        //public int idDog
        //{
        //    get
        //    {
        //        var member = ServiceFactory.Instance.ExpositionMembersService.GetById(this.IdExpositionMember);
        //        return Mapper.Map<models.Dog>(ServiceFactory.Instance.DogsService.GetById(member.IdDog)).Id;
        //    }
        //}
        //public models.Exposition GetDog
        //{
        //    get
        //    {
        //        var member = ServiceFactory.Instance.ExpositionMembersService.GetById(this.);
        //        return Mapper.Map<models.Dog>(ServiceFactory.Instance.DogsService.GetById(member.IdDog));
        //    }
        //}
    }
}

trunk/src/DogsClub.WebUI/Controllers/ExpositionWinnerController.cs
using AutoMapper;
using DogsClub.WebUI.Infrastracture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using models = DogsClub.WebUI.Models;

namespace DogsClub.WebUI.Controllers
{
    public class ExpositionWinnerController : Controller
    {
        public ActionResult Add(int idExpoition)
      {
            if (idExpoition != 0)
            {
                IEnumerable<models.Exposition> oldExp = Mapper.Map<IEnumerable<models.Exposition>>(ServiceFactory.Instance.ExpositionService.GetAll());
                models.Exposition itemExposition = oldExp.FirstOrDefault(t => t.Id == idExpoition);
                ViewData["allMember"] = itemExposition.GetDogsExpositionMembers;

                List<models.Avard> allAvard = Mapper.Map<List<models.Avard>>(ServiceFactory.Instance.AvardsService.GetAll());
                ViewData["allAvard"] = allAvard;

                ViewData["idExposition"] = itemExposition.Id;

            }
            return View();
        }

        [HttpPost]
        public ActionResult Add(models.ExpositionWinner winner, string idExposition, int idMember)
        {
            if (ModelState.IsValid && idExposition != null && idMember != 0)
            {

                models.Exposition oldExp = Mapper.Map<models.Exposition>(ServiceFactory.Instance.ExpositionService.GetById(Convert.ToInt32(idExposition)));
                List<models.ExpositionWinner> res = new List<models.ExpositionWinner>();

                models.ExpositionMember member = oldExp.GetMembers.FirstOrDefault(item => item.IdExposition == Convert.ToInt32(idExposition) && item.IdDog == idMember);
                ViewData["allMember"] = oldExp.GetDogsExpositionMembers;

                List<models.Avard> allAvard = Mapper.Map<List<models.Avard>>(ServiceFactory.Instance.AvardsService.GetAll());
                ViewData["allAvard"] = allAvard;

                res = member.GetExpositionWinner.Where(item => item.IdExpositionMember == member.Id).ToList();
                if (res.Count != 0)
                {
                    ViewData["SecondVavue"] = "SecondVavue";
                    return View();
                }

                if (oldExp.GetDogsExpositionMembers.Any(t => t.Id == winner.IdExpositionMember))
                {
                    ViewData["NotMember"] = "NullMember";
                    return View();
                }

                winner.IdExpositionMember = member.Id;

                ServiceFactory.Instance.ExpositionWinnersService.Add(winner.ToDomainModel());

                return RedirectToAction("GetAllDogs", new { idExp = Convert.ToInt32(idExposition) });
            }
            return View();
        }

        public ActionResult GetAllDogs(int idExp)
        {
            if (idExp != 0)
            {
                models.Exposition oldExp = Mapper.Map<models.Exposition>(ServiceFactory.Instance.ExpositionService.GetById(idExp));

                return View(oldExp);
            }
            return View("Index", "Exposition");
        }

        public ActionResult Delete(int id)
        {
            if (id == 0)
                throw new ArgumentNullException();
            models.ExpositionWinner oldExpWin = Mapper.Map<models.ExpositionWinner>(ServiceFactory.Instance.ExpositionWinnersService.GetById(id));

            if (oldExpWin == null)
                throw new ArgumentNullException();

            ServiceFactory.Instance.ExpositionWinnersService.Remove(oldExpWin.Id);
            return RedirectToAction("GetAllDogs", new { idExp = oldExpWin.Id });
        }

        public ActionResult Edit(int id, int idExposition)
        {
            if (id != 0 && idExposition != 0)
            {
                models.ExpositionWinner oldWinner = Mapper.Map<models.ExpositionWinner>(ServiceFactory.Instance.ExpositionWinnersService.GetById(id));
                models.Exposition oldExp = Mapper.Map<models.Exposition>(ServiceFactory.Instance.ExpositionService.GetById(idExposition));
                ViewData["allMember"] = oldExp.GetDogsExpositionMembers;
                List<models.Avard> allAvard = Mapper.Map<List<models.Avard>>(ServiceFactory.Instance.AvardsService.GetAll());
                ViewData["allAvard"] = allAvard;
                return View(oldWinner);
            }
            return RedirectToAction("GetAllDogs", new { idExp = Convert.ToInt32(idExposition) });
        }

        [HttpPost]
        public ActionResult Edit(models.ExpositionWinner winner, string idExposition, int idMember)
        {
            if (ModelState.IsValid && idExposition != null && idMember != 0)
            {
                models.Exposition oldExp = Mapper.Map<models.Exposition>(ServiceFactory.Instance.ExpositionService.GetById(Convert.ToInt32(idExposition)));
                models.ExpositionMember member = oldExp.GetMembers.FirstOrDefault(item => item.IdExposition == Convert.ToInt32(idExposition) && item.IdDog == idMember);
                ViewData["allMember"] = oldExp.GetDogsExpositionMembers;

                List<models.Avard> allAvard = Mapper.Map<List<models.Avard>>(ServiceFactory.Instance.AvardsService.GetAll());
                ViewData["allAvard"] = allAvard;

                if (oldExp.GetDogsExpositionMembers.Any(t => t.Id == winner.IdExpositionMember))
                {
                    ViewData["NotMember"] = "NullMember";
                    return View();
                }
                winner.IdExpositionMember = member.Id;
                ServiceFactory.Instance.ExpositionWinnersService.Edit(winner.ToDomainModel());
                return RedirectToAction("GetAllDogs", new { idExp = Convert.ToInt32(idExposition) });
            }
            return View("Index", "Exposition");
        }
    }
}

trunk/src/DogsClub.WebUI/Views/ExpositionWinner/Add.cshtml
@model DogsClub.WebUI.Models.ExpositionWinner

@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";


    List<SelectListItem> allMember = new List<SelectListItem>();
    if (ViewData["AllMember"] != null) 
    {
        var res = ViewData["allMember"] as  IEnumerable <DogsClub.WebUI.Models.Dog>;
        allMember.AddRange(res.Select(item => new SelectListItem() { Text = item.Name, Value = item.Id.ToString()}));
    }

    List<SelectListItem> allAvard = new List<SelectListItem>();
    if (ViewData["allAvard"] != null) 
    {
        var res = ViewData["allAvard"] as IEnumerable<DogsClub.WebUI.Models.Avard>;
        allAvard.AddRange(res.Select(item => new SelectListItem() { Text = item.Name, Value = item.Id.ToString() }));
    }
}


<div>
    <div class="ConteinerAddExposition">
        @using (@Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="ConteinerChengeUser">
                @Html.Hidden("idExposition", ViewData["idExposition"])

                <div class="NameAdd">Участник</div>
                @Html.DropDownList("idMember", allMember, new { @class = "EditText2" })

                <div class="NameAdd">Место</div>
                @Html.ValidationMessageFor(model => model.WinnerPlace, "", new { @class = "validationMessage" })
                @Html.EditorFor(model => model.WinnerPlace, new { htmlAttributes = new { @class = "EditText2" } })

                <div class="NameAdd">Награда</div>
                @Html.DropDownList("idAvard", allAvard, new { @class = "EditText2" })

                <input type="submit" value="Добавить" class="btn btn-info" id="AddButton" />
            </div>
        }
    </div>
</div>

trunk/src/DogsClub.WebUI/Views/ExpositionWinner/Edit.cshtml
@model DogsClub.WebUI.Models.ExpositionWinner

@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";


    List<SelectListItem> allMember = new List<SelectListItem>();
    if (ViewData["AllMember"] != null)
    {
        var res = ViewData["allMember"] as IEnumerable<DogsClub.WebUI.Models.Dog>;
        if (res != null)
        {

            allMember.AddRange(res.Select(r => new SelectListItem() { Text = r.Name, Value = r.Id.ToString(), Selected = r.Id != Model.GetDog.Id ? false : true }));
        }
    }

    List<SelectListItem> allAvard = new List<SelectListItem>();
    if (ViewData["allAvard"] != null)
    {
        var res = ViewData["allAvard"] as IEnumerable<DogsClub.WebUI.Models.Avard>;
        if (res != null)
        {

            allAvard.AddRange(res.Select(item => new SelectListItem() { Text = item.Name, Value = item.Id.ToString(), Selected = item.Id != Model.IdAvard ? false : true }));

        }
    }
}
    <div>
        <div class="ConteinerAddExposition">
            @using (@Html.BeginForm("Edit","ExpositionWinner",FormMethod.Post))
            {
                @Html.HiddenFor(model => model.IdExpositionMember)
                @Html.AntiForgeryToken()
                <div class="ConteinerChengeUser">
                    @Html.Hidden("idExposition", ViewData["idExposition"])

                    <div class="NameAdd">Участник</div>
                        @Html.DropDownList("idMember", allMember, new { @class = "EditText2" })

                    <div class="NameAdd">Место</div>
                    @Html.ValidationMessageFor(model => model.WinnerPlace, "", new { @class = "validationMessage" })
                    @Html.EditorFor(model => model.WinnerPlace, new { htmlAttributes = new { @class = "EditText2" } })

                    <div class="NameAdd">Награда</div>
                    @Html.DropDownList("idAvard", allAvard, new { @class = "EditText2" })

                    <input type="submit" value="Изменить" class="btn btn-info" id="AddButton" />
                </div>
            }
        </div>
    </div>

trunk/src/DogsClub.WebUI/Views/ExpositionWinner/GetAllDogs.cshtml
@model DogsClub.WebUI.Models.Exposition
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";
}
@{
    ViewBag.Title = "GetAllDogs";
    List<DogsClub.WebUI.Models.ExpositionWinner> allWinner = new List<DogsClub.WebUI.Models.ExpositionWinner>();
    if (Model.GetWinners.Count != 0) 
    {
        for (int i = 0; i < Model.GetWinners.Count; i++)
        {
            for (int t = 0; t < Model.GetWinners[i].GetExpositionWinner.Count; t++)
            {
                allWinner.Add(Model.GetWinners[i].GetExpositionWinner[t]);
            }
        }
    }
  }
<link href="~/Content/DataTables-1.10.4/css/jquery.dataTables.css" rel="stylesheet" />
<div>
    <div class="newConteinerAddExposition">
             <span class="expositionWinner">
                @Html.ActionLink("Добавить победителя", "Add", new { idExpoition = Model.Id }, new { @class = "btn btn-info", @id = "addExpositionWinner" })
            </span>
            @Html.DisplayFor(modelItem => modelItem.Name)
            <span class="timeExposition">
                @Html.DisplayFor(modelItem => modelItem.DateStart)
            </span>
</div>
</div>
<div class="ConteinerAllwinners">
        <table class="table table-hover" id="table">
            <thead>
                <tr>
                    <th class="ZagName">
                        @Html.DisplayName("Питомец")
                    </th>
                    <th class="ZagName">
                        @Html.DisplayName("Хозяин")
                    </th>
                    <th class="ZagName">
                        @Html.DisplayName("Место")
                    </th>
                    <th class="ZagName">
                        @Html.DisplayName("Награда")
                    </th>
                    <th></th>
                </tr>
            </thead>
            @foreach (DogsClub.WebUI.Models.ExpositionWinner item in allWinner)
            {
                <tr>
                    <td class="ZagValue2">
                        @Html.DisplayFor(modelItem => item.GetDog.Name)
                    </td>
                    <td class="ZagValue2">
                        @Html.DisplayFor(modelItem => item.GetDog.GetUser.Email)
                    </td>
                    <td class="ZagValue2">
                        @Html.DisplayFor(modelItem => item.WinnerPlace)
                    </td>
                    <td class="ZagValue2">
                        @Html.DisplayFor(modelItem => item.GetAvard.Name)
                    </td>
                    <td class="ZagValue2">
                        @Html.ActionLink("Редактировать", "Edit", new { id = item.Id, idExposition =Model.Id }) |
                        @Html.ActionLink("Удалить", "Delete", new { id = item.Id }) 
                    </td>
                </tr>
            }
        </table>
    </div>
@section script {
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $("#table").dataTable({
                "language": {
                    "lengthMenu": "Отображать _MENU_ записей на странице",
                    "zeroRecords": "Извините, таблица пуста",
                    "info": "Страница _PAGE_ из _PAGES_",
                    "infoEmpty": "Нет доступных записей",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "next": "Следующая страница",
                        "previous": "Предыдущая страница"
                    },
                    "search": "Найти"
                }
            });
        });
    </script>
}