trunk/src/DogsClub.WebUI/Controllers/ReportsController.cs
using AutoMapper;
using DogsClub.Abstract;
using DogsClub.DomainModel.ReportsEntities;
using DogsClub.Fake;
using DogsClub.WebUI.Infrastracture;
using StructureMap;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using models = DogsClub.WebUI.Models;

namespace DogsClub.WebUI.Controllers
{
    public class ReportsController : Controller
    {
		private readonly IServicesFactory _factory = ServiceFactory.Instance;

        //public ReportsController()
        //{
        //    ObjectFactory.Initialize(x =>
        //    {
        //        x.For<IUsersRepo>().Use<UsersFakeRepo>();
        //        x.For<IDogsRepo>().Use<DogsFakeRepo>();
        //        x.For<IPaymentTypesRepo>().Use<PayTypesFakeRepo>();
        //    });
        //}

        public ActionResult Index()
        {
            return PartialView();
        }

        #region all dogs vaccinations
        public ActionResult AllDogsVaccination()
		{
			return View();
		}
	
        [HttpPost]
		public ActionResult AllDogsVaccinationData(DateTime? startPeriod, DateTime? endPeriod)
		{
            if(startPeriod == null || endPeriod == null)
            {
                return RedirectToAction("AllDogsVaccination");
            }
             List<models.Vaccination> allVaccination  = Mapper.Map<List<models.Vaccination>>(ServiceFactory.Instance.VaccinationsService.GetAll());
             List<models.Vaccination> itemAllVac = allVaccination.Where(item => item.DateVacination >= startPeriod && item.DateVacination <= endPeriod).ToList();
             ViewData["startPeriod"] = startPeriod;
             ViewData["endPeriod"] = endPeriod;
            return View(itemAllVac);
		}
        #endregion

        #region concrette dog vaccination
        public ActionResult DogVaccination()
        {
            List<models.Dog> allDog = Mapper.Map<List<models.Dog>>(ServiceFactory.Instance.DogsService.GetAll());
            ViewData["allDog"] = allDog;
            return View();
        }

        [HttpPost]
        public ActionResult DogVacccinationData(DateTime? startPeriod, DateTime? endPeriod, int idDog)
        {
            if(startPeriod == null || endPeriod == null || idDog == null)
            {
                return RedirectToAction("DogVaccination");
            }
            //var data = _factory.ReportsService.GetDogVaccinationStatistic(startPeriod.Value, endPeriod.Value, idDog.Value);
            List<models.Vaccination> allVaccionation = Mapper.Map<List<models.Vaccination>>(ServiceFactory.Instance.VaccinationsService.GetAll());
            List<models.Vaccination> itemAllVac = allVaccionation.Where(item => item.DateVacination >= startPeriod && item.DateVacination <= endPeriod && item.IdDog == idDog).ToList();
            models.Dog itemDog = Mapper.Map<models.Dog>(ServiceFactory.Instance.DogsService.GetById(idDog));
            ViewData["itemDog"] = itemDog;
            ViewData["startPeriod"] = startPeriod;
            ViewData["endPeriod"] = endPeriod;
            var jsonData = itemAllVac
                .Select(t => new
                {
                    Year = t.DateVacination.Value.Year,
                    Name = t.Name
                })
                .GroupBy(t => t.Year)
                .Select(t => new
                {
                    label = t.Key + " Год",
                    value = t.Count()
                });

            ViewData["jsonData"] = Json(jsonData.ToArray());

            return View(itemAllVac);
        }

        #endregion

        #region concrette user payments
        public ActionResult UserPayment()
        {
            List<models.User> allUser = Mapper.Map<List<models.User>>(ServiceFactory.Instance.UserService.GetAll());
            ViewData["allUsers"] = allUser;
            return View();
        }

        [HttpPost]
        public ActionResult UserPaymentReport(DateTime? startPeriod, DateTime? endPeriod, int idUser)
        {
            if(startPeriod == null || endPeriod == null || idUser == null)
            {
                return RedirectToAction("UserPayment");
            }
            //UserPaymentsStatistic report = _factory.ReportsService.GetUserPaymentStatistic(startPeriod.Value, endPeriod.Value, idUser.Value);
            ViewData["startPeriod"] = startPeriod;
            ViewData["endPeriod"] = endPeriod;
            List<models.Payment> allPayment = Mapper.Map<List<models.Payment>>(ServiceFactory.Instance.PaymentsService.GetAll()).ToList();
            List<models.Payment> itemUserAllPayments = allPayment.Where(t => t.UserId == idUser).ToList();
            models.User user = Mapper.Map<models.User>(ServiceFactory.Instance.UserService.GetById(idUser));
            ViewData["user"] = user;
            var jsonData = itemUserAllPayments
                .GroupBy(t => t.IdType)
                .Select(t => new
                {
                    label = t.Key,
                    value = t.Sum(x => x.PaySize)
                })
                .ToArray();
            var yearsGrouping = itemUserAllPayments
                .GroupBy(t => t.PayDate.Year)
                .Select(t => new
                {
                    y = t.Key.ToString(),
                    a = t.Sum(x => x.PaySize)
                })
                .ToArray();
            ViewData["jsonData"] = jsonData;
            ViewData["yearsGrouping"] = yearsGrouping;
            return View(itemUserAllPayments);




    //        var jsonData = report
    //.Payments
    //.GroupBy(t => t.PayType)
    //.Select(t => new
    //{
    //    label = t.Key,
    //    value = t.Sum(x => x.PaySize)
    //})
    //.ToArray();
    //        var yearsGrouping = report
    //            .Payments
    //            .GroupBy(t => t.PayDate.Year)
    //            .Select(t => new
    //            {
    //                y = t.Key.ToString(),
    //                a = t.Sum(x => x.PaySize)
    //            })
    //            .ToArray();
    //        ViewData["jsonData"] = jsonData;
    //        ViewData["yearsGrouping"] = yearsGrouping;
    //        return View(report);
        }
        #endregion

        #region all users payments
        public ActionResult AllUsersPayments()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AllUsersPaymentsReport(DateTime? startPeriod, DateTime? endPeriod)
        {
            if(startPeriod == null || endPeriod == null)
            {
                return RedirectToAction("AllUsersPayments");
            }
            ViewData["startPeriod"] = startPeriod;
            ViewData["endPeriod"] = endPeriod;
            List<models.Payment> allPayment = Mapper.Map<List<models.Payment>>(ServiceFactory.Instance.PaymentsService.GetAll());
            List<models.Payment> checkPayment = allPayment.Where(m => m.PayDate >= startPeriod && m.PayDate <= endPeriod).ToList();
            return View(checkPayment);
        }
        #endregion

        public ActionResult PaymentTypeReport()
        {
            List<models.PaymentType> allPaymentType = Mapper.Map<List<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
            ViewData["allPaymentType"] = allPaymentType;
            return View();
        }

        public ActionResult PaymentTypeReportData(DateTime? startPeriod, DateTime? endPeriod, int idPaymentType)
        {
            if(startPeriod == null || endPeriod == null || idPaymentType == null)
            {
                return RedirectToAction("PaymentTypeReport");
            }
            List<models.Payment> allPayment = Mapper.Map<List<models.Payment>>(ServiceFactory.Instance.PaymentsService.GetAll());
            List<models.Payment> checkPaiment = allPayment.Where(item => item.PayDate >= startPeriod && item.PayDate <= endPeriod && item.IdType == idPaymentType).ToList();
            ViewData["startPeriod"] = startPeriod;
            ViewData["endPeriod"] = endPeriod;
            models.PaymentType itemType = Mapper.Map<models.PaymentType>(ServiceFactory.Instance.PaymentTypesService.GetById(idPaymentType));
            ViewData["itemType"] = itemType;
            return View(checkPaiment);
        }
    }
}




  //#region concrette dog vaccination
  //      public ActionResult DogVaccination()
  //      {
  //          return View();
  //      }

  //      [HttpPost]
  //      public ActionResult DogVacccinationData(DateTime? startPeriod, DateTime? endPeriod, int? idDog)
  //      {
  //          if(startPeriod == null || endPeriod == null || idDog == null)
  //          {
  //              return RedirectToAction("DogVaccination");
  //          }
  //          var data = _factory.ReportsService.GetDogVaccinationStatistic(startPeriod.Value, endPeriod.Value, idDog.Value);
  //          var jsonData = data
  //              .Vaccinations
  //              .Select(t => new
  //              {
  //                  Year = t.Date.Value.Year,
  //                  Name = t.Name
  //              })
  //              .GroupBy(t => t.Year)
  //              .Select(t => new
  //              {
  //                  label = t.Key + " Год",
  //                  value = t.Count()
  //              });

  //          ViewData["jsonData"] = Json(jsonData.ToArray());

  //          return View(data);
  //      }

  //      #endregion

trunk/src/DogsClub.WebUI/Views/Reports/AllDogsVaccination.cshtml
<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";
}
<div class="FormReportVaccination">
    <div class="FormReportVaccinationHeader">Вакцинации питомцев</div>

@using (Html.BeginForm("AllDogsVaccinationData", "Reports", FormMethod.Post))
{
    <div class="NamePersonCab">C</div>
    @Html.TextBox("startPeriod", false, new { @class = "newValuePersonCab" });

    <div class="NamePersonCab">По</div>
    @Html.TextBox("endPeriod", DateTime.Now.ToShortDateString(), new { @class = "newValuePersonCab" });
    <input type="submit" id="AddButton2" value="Сформировать отчет" class="btn btn-info" />
}
</div>
<div class="reportContainer" id="reportContainer">

</div>

@section script{
<script src="~/DatePicker/DataPicker(1-10).js"></script>
<script src="~/DatePicker/DataPicker(1-11).js"></script>
<script src="~/DatePicker/MyScriptDatePicker.js"></script>
<script src="~/Scripts/bootstrap.js"></script>

<script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>

@*<script src="~/Scripts/bootstrapPager.js"></script>*@

	<script>

		var reportDataUrl = "@Url.Action("AllDogsVaccinationData", "Reports")";

		$(document).ready(function () {

			$("#createReport").click(function () {
				var startPeriod = $("#startPeriod").val();
				var endPeriod = $("#endPeriod").val();

				if (startPeriod === "" || endPeriod === "") {
					alert("Пожалуйста, заполните параметры отчета");
					return;
				}

				$.ajax({
					url: reportDataUrl,
					type: "POST",
					data: { startPeriod: startPeriod, endPeriod: endPeriod },
					beforeSend: function () {
						$("#reportContainer").html("Pапрос к базе данных!");
					},
					success: function (response) {
						$("#reportContainer").html(response);
						$("#tableReport").dataTable({
							"language": {
								"lengthMenu": "Отображать _MENU_ записей на странице",
								"zeroRecords": "Извините, таблица пуста",
								"info": "Страница _PAGE_ из _PAGES_",
								"infoEmpty": "Нет доступных записей",
								"infoFiltered": "(filtered from _MAX_ total records)",
								"paginate": {
								    "next": "Следующая страница",
								    "previous": "Предыдущая страница"
								},
								"search": "Найти"
							}
						});
					},
					error: function () {
						alert("При запросе к серверу произошла ошибка. Пожалуйста, попробуйте обновить страницу");
					}
				});
			});

		});

		$('#startPeriod').datepicker({
		    dateFormat: 'dd.mm.yy'
		});
		$(function () {
		    $("#startPeriod").datepicker();
		});
		$('#startPeriod').datepicker('option', $.datepicker.regional["ru"]);

		jQuery(function ($) {
		    $.datepicker.regional['ru'] = {
		        monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                'Октябрь', 'Ноябрь', 'Декабрь'],
		        dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
		        firstDay: 1,
		    };
		    $.datepicker.setDefaults($.datepicker.regional['ru']);
		});
		$.datepicker.setDefaults($.extend(
          $.datepicker.regional["ru"])
        );
	</script>

}

trunk/src/DogsClub.WebUI/Views/Reports/AllDogsVaccinationData.cshtml
@model List<DogsClub.WebUI.Models.Vaccination>
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";
    DateTime startPeriod = (DateTime)ViewData["startPeriod"];
    DateTime endPeriod = (DateTime)ViewData["endPeriod"];
}

<link href="~/Content/DataTables-1.10.4/css/jquery.dataTables.css" rel="stylesheet" />
<div class="ConteinerReportVaccination">
    <div class="FormReportVaccination">
        <span class="headerWer">Вакцинация </span>c @startPeriod.ToLongDateString() по @endPeriod.ToLongDateString()
    </div>
    <div class="graphic-wrap">
        <table class="table table-hover" id="tableReport">
            <thead>
                <tr>
                    <th class="ZagName">
                        Кличка
                    </th>
                    <th class="ZagName">
                        Парода
                    </th>
                    <th class="ZagName">
                        Пол
                    </th>
                    <th class="ZagName">
                        Возраст
                    </th>
                    <th class="ZagName">
                        Владелец
                    </th>
                    <th class="ZagName">
                        Прививка
                    </th>
                    <th class="ZagName">
                        Дата
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="ZagValue2">@item.GetDog.Name</td>
                        <td class="ZagValue2">@item.GetDog.DogType.Name</td>
                        <td class="ZagValue2">@item.GetDog.GetSex</td>
                        <td class="ZagValue2">@item.GetDog.Age</td>
                        <td class="ZagValue2">@item.GetDog.GetUser.LastName @item.GetDog.GetUser.FirstName @item.GetDog.GetUser.MiddleName</td>
                        <td class="ZagValue2">@item.Name</td>
                        <td class="ZagValue2">@item.DateVacination.Value.ToLongDateString()</td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>
@section script {
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $("#tableReport").dataTable({
                "language": {
                    "lengthMenu": "Отображать _MENU_ записей на странице",
                    "zeroRecords": "Извините, таблица пуста",
                    "info": "Страница _PAGE_ из _PAGES_",
                    "infoEmpty": "Нет доступных записей",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "next": "Следующая страница",
                        "previous": "Предыдущая страница"
                    },
                    "search": "Найти"
                }
            });
        })
    </script>
}

trunk/src/DogsClub.WebUI/Views/Reports/AllUsersPayments.cshtml
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";
}
<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
<div class="FormReportVaccination">
    <div class="FormReportVaccinationHeader">Платежи участинков клуба</div>

    @using (Html.BeginForm("AllUsersPaymentsReport", "Reports", FormMethod.Post))
    {
        <div class="NamePersonCab">C</div>
        @Html.TextBox("startPeriod", false, new { @class = "newValuePersonCab" });

        <div class="NamePersonCab">По</div>
        @Html.TextBox("endPeriod", DateTime.Now.ToShortDateString(), new { @class = "newValuePersonCab" });
        <input type="submit" id="AddButton2" value="Сформировать отчет" class="btn btn-info" />
    }
    </div>

    @section script{
        <script src="~/DatePicker/DataPicker(1-10).js"></script>
        <script src="~/DatePicker/DataPicker(1-11).js"></script>
        <script src="~/DatePicker/MyScriptDatePicker.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>

        <script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>

        @*<script src="~/Scripts/bootstrapPager.js"></script>*@

        <script>
            $('#startPeriod').datepicker({
                dateFormat: 'dd.mm.yy'
            });
            $(function () {
                $("#startPeriod").datepicker();
            });
            $('#startPeriod').datepicker('option', $.datepicker.regional["ru"]);

            jQuery(function ($) {
                $.datepicker.regional['ru'] = {
                    monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                    'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                    'Октябрь', 'Ноябрь', 'Декабрь'],
                    dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                    firstDay: 1,
                };
                $.datepicker.setDefaults($.datepicker.regional['ru']);
            });
            $.datepicker.setDefaults($.extend(
              $.datepicker.regional["ru"])
            );
        </script>
    }


trunk/src/DogsClub.WebUI/Views/Reports/AllUsersPaymentsReport.cshtml
@model List<DogsClub.WebUI.Models.Payment>
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";
    DateTime startPeriod = (DateTime)ViewData["startPeriod"];
    DateTime endPeriod = (DateTime)ViewData["endPeriod"];
}
<link href="~/Content/themes/base/theme.css" rel="stylesheet" />
<link href="~/Content/themes/base/core.css" rel="stylesheet" />
<link href="~/Content/themes/base/accordion.css" rel="stylesheet" />

<link href="~/Content/DataTables-1.10.4/css/jquery.dataTables.css" rel="stylesheet" />
<div class="ConteinerReportVaccination">
    <div class="FormReportVaccination">
        <span class="headerWer">Платежи всех участников клуба за период </span>c @startPeriod.ToLongDateString() по @endPeriod.ToLongDateString()
    </div>
    <div class="graphic-wrap">
        <table class="table table-hover" id="tableReport">
            <thead>
                <tr>
                    <th class="ZagName">
                        Дата платежа
                    </th>
                    <th class="ZagName">
                        Тип платежа
                    </th>
                    <th class="ZagName">
                        Размер платежа
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="ZagValue2">@item.PayDate</td>
                        <td class="ZagValue2">@item.GetType.Name</td>
                        <td class="ZagValue2">@item.PaySize</td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

@section script {
    <script src="~/Scripts/jquery-ui-1.11.4.js"></script>
    <script>
        $(document).ready(function () {
            $("#accordion").accordion();
        });
    </script>
}

trunk/src/DogsClub.WebUI/Views/Reports/DogVaccination.cshtml
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";

        List<SelectListItem> allDog = new List<SelectListItem>();
        if (ViewData["allDog"] != null)
        {
            var a = ViewData["allDog"] as IEnumerable<DogsClub.WebUI.Models.Dog>;
            if (a != null)
            {
                allDog.AddRange(a.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString()}));
            }
        }

}
<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
<link href="~/Content/DataTables-1.10.4/css/jquery.dataTables.css" rel="stylesheet" />

<div class="FormReportVaccination">
    <div class="FormReportVaccinationHeader">Вакцинация конкретной собаки</div>

    @using (Html.BeginForm("DogVacccinationData", "Reports", FormMethod.Post))
    {
        <div class="NamePersonCab">C</div>
        @Html.TextBox("startPeriod", false, new { @class = "newValuePersonCab" });

       <div class="NamePersonCab">По</div>
        @Html.TextBox("endPeriod", DateTime.Now.ToShortDateString(),  new { @class = "newValuePersonCab" });
         <div class="NamePersonCab">Выберите питомца</div>
        @Html.DropDownList("idDog", allDog, new { @class = "newValuePersonCab" })
    <input type="submit" id="AddButton2" value="Сформировать отчет" class="btn btn-info" />
    }
</div>

@section script{
<script src="~/DatePicker/DataPicker(1-10).js"></script>
<script src="~/DatePicker/DataPicker(1-11).js"></script>
<script src="~/DatePicker/MyScriptDatePicker.js"></script>
<script src="~/Scripts/bootstrap.js"></script>

    <script>

        $('#startPeriod').datepicker({
		    dateFormat: 'dd.mm.yy'
		});
		$(function () {
		    $("#startPeriod").datepicker();
		});
		$('#startPeriod').datepicker('option', $.datepicker.regional["ru"]);

		jQuery(function ($) {
		    $.datepicker.regional['ru'] = {
		        monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                'Октябрь', 'Ноябрь', 'Декабрь'],
		        dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
		        firstDay: 1,
		    };
		    $.datepicker.setDefaults($.datepicker.regional['ru']);
		});
		$.datepicker.setDefaults($.extend(
          $.datepicker.regional["ru"])
        );
	</script>

}

trunk/src/DogsClub.WebUI/Views/Reports/PaymentTypeReport.cshtml
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";

    List<SelectListItem> allPaymentType = new List<SelectListItem>();
    if (ViewData["allPaymentType"] != null)
    {
        var a = ViewData["allPaymentType"] as IEnumerable<DogsClub.WebUI.Models.PaymentType>;
        if (a != null)
        {
            allPaymentType.AddRange(a.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString() }));
        }
    }

}
<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
<div class="FormReportVaccination">
    <div class="FormReportVaccinationHeader">Платежи по типу</div>

    @using (Html.BeginForm("PaymentTypeReportData", "Reports", FormMethod.Post))
    {
        <div class="NamePersonCab">C</div>
        @Html.TextBox("startPeriod", false, new { @class = "newValuePersonCab" });

        <div class="NamePersonCab">По</div>
        @Html.TextBox("endPeriod", DateTime.Now.ToShortDateString(), new { @class = "newValuePersonCab" });
        <div class="NamePersonCab">Тип платежа</div>
        @Html.DropDownList("idPaymentType", allPaymentType, new { @class = "newValuePersonCab" })
        <input type="submit" id="AddButton2" value="Сформировать отчет" class="btn btn-info" />
    }
</div>
@section script{
    <script src="~/DatePicker/DataPicker(1-10).js"></script>
    <script src="~/DatePicker/DataPicker(1-11).js"></script>
    <script src="~/DatePicker/MyScriptDatePicker.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

    <script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>

    <script>


        $('#startPeriod').datepicker({
            dateFormat: 'dd.mm.yy'
        });
        $(function () {
            $("#startPeriod").datepicker();
        });
        $('#startPeriod').datepicker('option', $.datepicker.regional["ru"]);

        jQuery(function ($) {
            $.datepicker.regional['ru'] = {
                monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                'Октябрь', 'Ноябрь', 'Декабрь'],
                dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                firstDay: 1,
            };
            $.datepicker.setDefaults($.datepicker.regional['ru']);
        });
        $.datepicker.setDefaults($.extend(
          $.datepicker.regional["ru"])
        );
    </script>
}


@*<h2>Платежи по типу</h2>

@using (Html.BeginForm("PaymentTypeReportData", "Reports", FormMethod.Post))
{
    @Html.TextBox("startPeriod")
    @Html.TextBox("endPeriod", DateTime.Now.ToShortDateString())
    @Html.TextBox("idPaymentType")
    <input type="submit" id="createReport" value="Сформировать отчет" />
}*@





trunk/src/DogsClub.WebUI/Views/Reports/UserPayment.cshtml
<link href="~/DatePicker/jquery-ui-DatePicker.css" rel="stylesheet" />
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";

    Layout = "~\\Views\\Shared\\_Layout4.cshtml";

    List<SelectListItem> allUsers = new List<SelectListItem>();
        if (ViewData["allUsers"] != null)
        {
            var a = ViewData["allUsers"] as IEnumerable<DogsClub.WebUI.Models.User>;
            if (a != null)
            {
                allUsers.AddRange(a.Select(t => new SelectListItem() { Text = t.LastName + t.FirstName + t.MiddleName, Value = t.Id.ToString() }));
            }
        }    
}
<div class="FormReportVaccination">
    <div class="FormReportVaccinationHeader">Платежи пользователя</div>

    @using (Html.BeginForm("UserPaymentReport", "Reports", FormMethod.Post))
    {
        <div class="NamePersonCab">C</div>
        @Html.TextBox("startPeriod", false, new { @class = "newValuePersonCab" });

        <div class="NamePersonCab">По</div>
        @Html.TextBox("endPeriod", DateTime.Now.ToShortDateString(), new { @class = "newValuePersonCab" });


    <div class="NamePersonCab">Пользователля</div>
    @Html.DropDownList("idUser", allUsers, new { @class = "newValuePersonCab" })

    <input type="submit" id="AddButton2" value="Сформировать отчет" class="btn btn-info" />
    }
</div>

@section script{
    <script src="~/DatePicker/DataPicker(1-10).js"></script>
    <script src="~/DatePicker/DataPicker(1-11).js"></script>
    <script src="~/DatePicker/MyScriptDatePicker.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

    <script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>

    <script>
		$('#startPeriod').datepicker({
		    dateFormat: 'dd.mm.yy'
		});
		$(function () {
		    $("#startPeriod").datepicker();
		});
		$('#startPeriod').datepicker('option', $.datepicker.regional["ru"]);

		jQuery(function ($) {
		    $.datepicker.regional['ru'] = {
		        monthNames: ['Яварь', 'Февраль', 'Март', 'Апрель',
                'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь',
                'Октябрь', 'Ноябрь', 'Декабрь'],
		        dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
		        firstDay: 1,
		    };
		    $.datepicker.setDefaults($.datepicker.regional['ru']);
		});
		$.datepicker.setDefaults($.extend(
          $.datepicker.regional["ru"])
        );
    </script>
}