trunk/src/DogsClub.WebUI/Controllers/PaymentTypeController.cs
using AutoMapper;
using DogsClub.WebUI.Infrastracture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using models = DogsClub.WebUI.Models;

namespace DogsClub.WebUI.Controllers
{
    public class PaymentTypeController : Controller
    {



        private List<models.PaymentsPeriodType> GetPeriod()
        {
            var res = ServiceFactory.Instance.PaymentTypesService.GetAllPaymentPeriods();
            List<models.PaymentsPeriodType> all = new List<models.PaymentsPeriodType>();

            foreach (var item in res)
            {
                all.Add(new models.PaymentsPeriodType() { Id = item.Id, Name = item.Name });
            }
            return all;
        }
        // GET: PaymentType
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAll()
        {
            IEnumerable<models.PaymentType> allPaymentType = Mapper.Map<IEnumerable<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
            return PartialView(allPaymentType);
        }


        public ActionResult Add()
        {
            ViewData["allPeriod"] = GetPeriod();
            return PartialView();
        }
        [HttpPost]
        public ActionResult Add(models.PaymentType itemPaymentType)
        {
            ViewData["allPeriod"] = GetPeriod();
            if (ModelState.IsValid )
            {
                IEnumerable<models.PaymentType> allPaymentType = Mapper.Map<IEnumerable<models.PaymentType>>(ServiceFactory.Instance.PaymentTypesService.GetAll());
                var avard = allPaymentType.FirstOrDefault(t => t.Name == itemPaymentType.Name && t.IdPeriod == itemPaymentType.IdPeriod);
                if (avard != null)
                {
                    ViewData["ValueAvard"] = "notNull";
                    return RedirectToAction("Index");
                }
                ServiceFactory.Instance.PaymentTypesService.Add(itemPaymentType.ToDomainModel());
                IEnumerable<models.Dog> modelsVac = Mapper.Map<IEnumerable<models.Dog>>(ServiceFactory.Instance.DogsService.GetAll());
                return PartialView();
            }
            return PartialView();
        }

        public ActionResult Edit(int idPaymentType)
        {
            if (idPaymentType != 0)
            {
                models.PaymentType payment = Mapper.Map<models.PaymentType>(ServiceFactory.Instance.PaymentTypesService.GetById(idPaymentType));
                ViewData["allPeriod"] = GetPeriod();
                return View(payment);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Edit(models.PaymentType itemPaymentType)
        {
            ViewData["allPeriod"] = GetPeriod();
            if (ModelState.IsValid )
            {
                ServiceFactory.Instance.PaymentTypesService.Edit(itemPaymentType.ToDomainModel());
                return RedirectToAction("Index");
            }
            return View(itemPaymentType);
        }
        public ActionResult Remove(int idPaymentType)
        {
            if (idPaymentType != 0)
            {
                models.PaymentType oldvac = Mapper.Map<models.PaymentType>(ServiceFactory.Instance.PaymentTypesService.GetById(idPaymentType));
                if (oldvac == null)
                    throw new ArgumentNullException();
                ServiceFactory.Instance.PaymentTypesService.Remove(oldvac.Id);
            }
            return RedirectToAction("Index");
        }
    }
}

trunk/src/DogsClub.WebUI/Views/PaymentType/Add.cshtml
@model DogsClub.WebUI.Models.PaymentType
@{
    List<SelectListItem> allPeriod = new List<SelectListItem>();
    var a = ViewData["allPeriod"] as IEnumerable<DogsClub.WebUI.Models.PaymentsPeriodType>;
    if (a != null)
    {
        allPeriod.AddRange(a.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString() }));
    }
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="ConteinerChengeUser">
        @Html.AntiForgeryToken()

        <div class="NameAdd">Название</div>
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "validationMessage" })
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "EditText2" } })

        <div class="NameAdd ">Выберите период</div>
        @Html.DropDownList("IdPeriod", allPeriod, new { @class = "EditText2" })

        <input type="submit" value="Добавить" class="btn btn-info" id="AddButton" />
    </div>
}


trunk/src/DogsClub.WebUI/Views/PaymentType/Edit.cshtml
@model DogsClub.WebUI.Models.PaymentType
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";

    List<SelectListItem> allPeriod = new List<SelectListItem>();
    var a = ViewData["allPeriod"] as IEnumerable<DogsClub.WebUI.Models.PaymentsPeriodType>;
    if (a != null)
    {
        allPeriod.AddRange(a.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString() }));
    }
 }

<div>
    <div class="ConteinerAddExposition">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="ConteinerChengeUser">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="NameAdd">Название</div>
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "EditText2" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

        <div class="NameAdd">Питомец</div>
        @Html.DropDownList("IdPeriod", allPeriod, new { @class = "EditText2" })

        <input type="submit" value="Изменить" class="btn btn-info" id="AddButton" />
    </div>
}
    </div>
</div>

@section script{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

trunk/src/DogsClub.WebUI/Views/PaymentType/GetAll.cshtml
@model IEnumerable<DogsClub.WebUI.Models.PaymentType>
<link href="~/Content/DataTables-1.10.4/css/jquery.dataTables.css" rel="stylesheet" />
<div class="ConteinerUserList">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="ZagName">
                    @Html.DisplayName("Имя")
                </th>
                <th class="ZagName">
                    @Html.DisplayName("Период")
                </th>
                <th class="ZagName">
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="ZagValue2">
                        @Html.DisplayFor(modelsItem => item.Name)
                    </td>
                    <td class="ZagValue2">
                        @Html.DisplayFor(modelsItem => item.GetPeriod.Name)
                    </td>
                    <td class="ZagValue2">
                        @Html.ActionLink("Редактировать", "Edit", new { idPaymentType = item.Id }) |
                        @Html.ActionLink("Удалить", "Remove", new { idPaymentType = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section script {
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>
    <script src="~/DatePicker/DataPicker(1-10).js"></script>
    <script src="~/DatePicker/DataPicker(1-11).js"></script>
    <script src="~/DatePicker/MyScriptDatePicker.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $(document).ready(function () {
            $("#table").dataTable({
                "language": {
                    "lengthMenu": "Отображать _MENU_ записей на странице",
                    "zeroRecords": "Извините, таблица пуста",
                    "info": "Страница _PAGE_ из _PAGES_",
                    "infoEmpty": "Нет доступных записей",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "next": "Следующая страница",
                        "previous": "Предыдущая страница"
                    },
                    "search": "Найти"
                }
            });
        });
    </script>
}



trunk/src/DogsClub.WebUI/Views/PaymentType/Index.cshtml
@{
    Layout = "~\\Views\\Shared\\_Layout4.cshtml";
}
<div>
    <div class="ConteinerAddExposition">
        @Html.Action("Add", "PaymentType")
    </div>
    <div class="newConteinerVaccination">
        @Html.Action("GetAll", "PaymentType")
    </div>
</div>